trigger:
  batch: true
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: CI
    timeoutInMinutes: 10

    workspace:
      clean: all

    steps:
      - task: UseDotNet@2
        displayName: "Use .NET Core 3.1 SDK"
        inputs:
          packageType: sdk
          version: 3.1.x

      - task: UseDotNet@2
        displayName: "Use .NET 6 SDK"
        inputs:
          packageType: sdk
          version: 6.0.x

      - task: PowerShell@2
        displayName: "Restore, build, test and pack"
        inputs:
          targetType: "filePath"
          filePath: "build.ps1"