using System.Diagnostics.CodeAnalysis;
using MongoDB.Bson;
using MongoDB.Bson.Serialization.Attributes;

namespace GSoft.Infra.Mongo;

public abstract class MongoDocument : IMongoDocument
{
    [BsonId]
    [BsonIgnoreIfDefault]
    [BsonRepresentation(BsonType.ObjectId)]
    [SuppressMessage("ReSharper", "NullableWarningSuppressionIsUsed", Justification = "The ID will be generated by Mongo and should not be used before.")]
    public string Id { get; set; } = null!;
}