name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "6.0.x"
          source-url: ${{ secrets.NUGET_DEV_SOURCE }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GSOFT_NUGET_API_KEY }}

      - run: ./Build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_DEV_SOURCE }}
          NUGET_API_KEY: ${{ secrets.GSOFT_NUGET_API_KEY }}
