name: CI

on:
  pull_request:
    branches: ["main"]
  
  push:
    branches:
      - "renovate/**"

# Prevent duplicate runs if Renovate falls back to creating a PR
concurrency:
  group: ${{ github.workflow }}-${{github.event_name}}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  main:
    # As of 18/12/2024, Ephemeral Mongo supports only MongoDB 6.0, which is compatible only with Ubuntu 22.04 (https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/)
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-dotnet@v4
        with:
          source-url: ${{ secrets.NUGET_GSOFTDEV_FEED_URL }}
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GSOFT_NUGET_API_KEY }}

      - run: ./Build.ps1
        shell: pwsh
        env:
          NUGET_SOURCE: ${{ secrets.NUGET_GSOFTDEV_FEED_URL }}
          NUGET_API_KEY: ${{ secrets.GSOFT_NUGET_API_KEY }}

  linearb:
    needs: [main]
    uses: workleap/wl-reusable-workflows/.github/workflows/linearb-deployment.yml@main
    with:
      environment: development
    secrets: inherit
